function setKey(
  value: string,
  upperCase: string | null,
  widthRate: number = 1,
  isEnable: boolean = true,
) {
  return {
    value,
    upperCase,
    widthRate,
    isEnable,
  };
}

interface IKeys {
  [index: string]: {
    value: string;
    upperCase: string | null;
    widthRate: number;
    isEnable: boolean;
  };
}

export const keys: IKeys = {
  "`": setKey("`", "~", 1, false),
  "1": setKey("1", "!"),
  "2": setKey("2", "@"),
  "3": setKey("3", "#"),
  "4": setKey("4", "$"),
  "5": setKey("5", "%"),
  "6": setKey("6", "^"),
  "7": setKey("7", "&"),
  "8": setKey("8", "*"),
  "9": setKey("9", "("),
  "0": setKey("0", ")"),
  "-": setKey("-", "_"),
  "=": setKey("=", "+"),
  Backspace: setKey("←", null, 2),
  Tab: setKey("Tab", null, 1.5, false),
  q: setKey("Q", "Q"),
  w: setKey("W", "W"),
  e: setKey("E", "E"),
  r: setKey("R", "R"),
  t: setKey("T", "T"),
  y: setKey("Y", "Y"),
  u: setKey("U", "U"),
  i: setKey("I", "I"),
  o: setKey("O", "O"),
  p: setKey("P", "P"),
  "[": setKey("[", "{"),
  "]": setKey("]", "}"),
  "\\": setKey("\\", "|", 1.5, false),
  CapsLock: setKey("CapsLock", null, 1.8, false),
  a: setKey("A", "A"),
  s: setKey("S", "S"),
  d: setKey("D", "D"),
  f: setKey("F", "F"),
  g: setKey("G", "G"),
  h: setKey("H", "H"),
  j: setKey("J", "J"),
  k: setKey("K", "K"),
  l: setKey("L", "L"),
  ";": setKey(";", ":"),
  "'": setKey("'", '"'),
  Enter: setKey("Enter", null, 2.2, false),
  Shift: setKey("Shift", null, 2.5, false),
  z: setKey("Z", "Z"),
  x: setKey("X", "X"),
  c: setKey("C", "C"),
  v: setKey("V", "V"),
  b: setKey("B", "B"),
  n: setKey("N", "N"),
  m: setKey("M", "M"),
  ",": setKey(",", "<"),
  ".": setKey(".", "."),
  "/": setKey("/", "/"),
  Control: setKey("Ctrl", null, 1.5, false),
  Fn: setKey("Fn", null, 1.5, false),
  Alt: setKey("Alt", null, 1.5, false),
  " ": setKey(" ", null, 5.5),
  HangulMode: setKey("한/영", null, 1.5, false),
  Meta: setKey("win", null, 1.5, false),
  HanjaMode: setKey("한자", null, 1.5, false),

  Q: setKey("Q", "Q"),
  W: setKey("W", "W"),
  E: setKey("E", "E"),
  R: setKey("R", "R"),
  T: setKey("T", "T"),
  Y: setKey("Y", "Y"),
  U: setKey("U", "U"),
  I: setKey("I", "I"),
  O: setKey("O", "O"),
  P: setKey("P", "P"),
  A: setKey("A", "A"),
  S: setKey("S", "S"),
  D: setKey("D", "D"),
  F: setKey("F", "F"),
  G: setKey("G", "G"),
  H: setKey("H", "H"),
  J: setKey("J", "J"),
  K: setKey("K", "K"),
  L: setKey("L", "L"),
  Z: setKey("Z", "Z"),
  X: setKey("X", "X"),
  C: setKey("C", "C"),
  V: setKey("V", "V"),
  B: setKey("B", "B"),
  N: setKey("N", "N"),
  M: setKey("M", "M"),
};

export const lines = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  ["Tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "\\"],
  ["CapsLock", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'", "Enter"],
  ["Shift", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "Shift"],
  ["Control", "Fn", "Alt", " ", "Alt", "HangulMode", "Meta", "HanjaMode"],
];
